dist: trusty
language: node_js
node_js:
- stable
 script:
 - npm run coverage
 branches:
    only: development
notifications:
 email:
    recipients:
    karimifazlu50@gmail.com
    on_success: never        # default: change
    on_failure: always       # default: always
